### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by loitanvo** [nithincvpoyyil/mixpanel-tools#10]
Since the API changed the request URL is now:

api-js.mixpanel.com/track/?ip=

Instead of 

api-js.mixpanel.com/track/?data=

Since this change it is no longer picking up the network calls.

**Comment by Mad-Chemist** [comment]
Was wondering why this stopped working.. and right when I needed it too!  😬

**Comment by nithincvpoyyil** [comment]
@loitanvo , @Mad-Chemist : Hi Guys, I have updated the API URLs in the last December only. closing this issue now. Thanks for the feedback.
