### ISSUE TITLE
Where to find this?

### ISSUE THREAD

**Issue by boryn** [nithincvpoyyil/mixpanel-tools#16]
Please provide a picture in Chrome Web Store where to actually find this tool after installing:
[https://www.screencast.com/t/StGXzMhKKrWQ](https://www.screencast.com/t/StGXzMhKKrWQ)

**Comment by boryn** [comment]
Additionally, I had to restart the browser to see this menu item

**Comment by nithincvpoyyil** [comment]
@boryn: I will update that 👍

**Comment by nithincvpoyyil** [comment]
Added screenshot and description
