### ISSUE TITLE
Chrome webstore older version

### ISSUE THREAD

**Issue by OFFLlNE** [nithincvpoyyil/mixpanel-tools#18]
Hi

It looks like the 22May 2020 release was version 0.7
But on my Chrome extensions I can only see version 0.6

Experiencing the issues that there are no events being shown in the tool :(

**Comment by OFFLlNE** [comment]
![image](https://user-images.githubusercontent.com/8721312/104428134-c42d0800-558c-11eb-9854-dfe7001c033b.png)

**Comment by nithincvpoyyil** [comment]
@OFFLlNE : are you trying to connect to Mixpanel  EU APIs?

**Comment by nithincvpoyyil** [comment]
There is a problem in version mismatch, EU API update is coming soon. Submitted for review.

**Comment by nithincvpoyyil** [comment]
Done.
