### ISSUE TITLE
Add a setting to support any URL with self-hosted tracking

### ISSUE THREAD

**Issue by christophehurpeau** [nithincvpoyyil/mixpanel-tools#20]
Hello,

We use [self-hosted tracking](https://developer.mixpanel.com/docs/self-hosted-tracking) and I can't seem to find an option to configure our custom url, would this be possible ?

Thanks

**Comment by nithincvpoyyil** [comment]
@christophehurpeau : Thanks for the feedback, let me check the options.

**Comment by nithincvpoyyil** [comment]
Hi @christophehurpeau : Added a self-hosted URL field in the header-nav, you can use this for custom proxy URL.  New Version is updated in the web-store. Please check and let me know.  

<img width="795" alt="Screenshot 2021-07-16 at 7 28 29 pm" src="https://user-images.githubusercontent.com/5662018/125959761-b5d63b81-23aa-4021-8d7d-d7577a19a37c.png">

**_`Hopes this will help you.  Please  star the repo, if you found this extension helpful.`_** 

- Nithin

**Comment by nithincvpoyyil** [comment]
[update] : layout is not fully responsive, resize the devtool window if its not visible.
