### ISSUE TITLE
No events as of today

### ISSUE THREAD

**Issue by hofnigar** [nithincvpoyyil/mixpanel-tools#23]
Hi - thank u all for this very useful tool. 
as of today I don't see any events being reported in the Mixpanel Tools.
could u pls help? 
TNX!

**Comment by hofnigar** [comment]
after communicating with Mixpanel - it seems that it is possibly due to a release they've made 4 days ago 
https://github.com/mixpanel/mixpanel-js/releases/tag/v2.43.0

I hope it helps

**Comment by nithincvpoyyil** [comment]
@hofnigar - Issue has been addressed in #25, so closing this issue.

**Comment by nithincvpoyyil** [comment]
The extension was submitted for review
