### ISSUE TITLE
Remember my last self-hosted URL setting

### ISSUE THREAD

**Issue by Rifdhan** [nithincvpoyyil/mixpanel-tools#28]
Is it possible to have the extension remember my last setting for the self-hosted URL field? If it can remember it on a per-website basis that would be even better, but I'd be happy with a global saved value too.

Currently I have to set that field every time I open Dev Tools on a new tab 😅

Referring to this input field: https://github.com/nithincvpoyyil/mixpanel-tools/issues/20

**Comment by nithincvpoyyil** [comment]
@Rifdhan : Thanks for reporting the issue, I will add this to the next features list.

**Comment by daroczig** [comment]
This would be indeed fantastic :bow:

**Comment by nithincvpoyyil** [comment]
@daroczig , @Rifdhan : Added this feature to new version. Closing this issue now
