### ISSUE TITLE
Mixpanel updated structure again

### ISSUE THREAD

**Issue by loitanvo** [nithincvpoyyil/mixpanel-tools#7]
Hey there! 

love your app! I just wanted to report:

Mixpanel changed their URL structure again. It is now 

https://api-js.mixpanel.com/track/?ip=

instead of 

https://api-js.mixpanel.com/track/?data=

**Comment by nithincvpoyyil** [comment]
@loitanvo  -  Thank you for reporting, let me check.

**Comment by nithincvpoyyil** [comment]
`https://api-js.mixpanel.com/track/?ip=1&_=xxxxxxx ` I guess this url is just pinging to the mixpanel APIs and it has no data associated with it.

**Comment by nithincvpoyyil** [comment]
@loitanvo : Closing this issue, because currently we are is avoiding above request pattern, as it is not sending any details. Thanks for reporting this issue. - Nithin
