### ISSUE TITLE
No events 

### ISSUE THREAD

**Issue by babipal** [nithincvpoyyil/mixpanel-tools#9]
Hi, 
Thanks for this very useful tool. As of just a few days ago, it was working fine, now I don't see any events being reported in the Mixpanel Tools. 
thanks

**Comment by nithincvpoyyil** [comment]
@babipal : I am working on this, changes were made for the API changes. The new package will be published soon. Thank you for your feedback.  Meanwhile, if you like, you can use the developer mode option. Please see the link- https://github.com/nithincvpoyyil/mixpanel-tools/blob/master/dev-bundle/readme.MD

**Comment by nithincvpoyyil** [comment]
Hi @babipal, the latest version is published, with bug fixes.

**Comment by babipal** [comment]
Thanks for the updates.
